# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PaintView.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PaintWindow(object):
    def setupUi(self, PaintWindow):
        PaintWindow.setObjectName("PaintWindow")
        PaintWindow.resize(600, 450)
        self.centralwidget = QtWidgets.QWidget(PaintWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.AddButton = QtWidgets.QPushButton(self.centralwidget)
        self.AddButton.setGeometry(QtCore.QRect(20, 340, 80, 40))
        self.AddButton.setObjectName("AddButton")
        self.InitializeButton = QtWidgets.QPushButton(self.centralwidget)
        self.InitializeButton.setGeometry(QtCore.QRect(160, 340, 80, 40))
        self.InitializeButton.setObjectName("InitializeButton")
        self.UpdateButton = QtWidgets.QPushButton(self.centralwidget)
        self.UpdateButton.setGeometry(QtCore.QRect(300, 340, 80, 40))
        self.UpdateButton.setObjectName("UpdateButton")
        self.ViewBox = QtWidgets.QGroupBox(self.centralwidget)
        self.ViewBox.setGeometry(QtCore.QRect(10, 140, 111, 191))
        self.ViewBox.setObjectName("ViewBox")
        self.leftButton = QtWidgets.QCheckBox(self.ViewBox)
        self.leftButton.setGeometry(QtCore.QRect(10, 20, 82, 17))
        self.leftButton.setObjectName("leftButton")
        self.rightButton = QtWidgets.QCheckBox(self.ViewBox)
        self.rightButton.setGeometry(QtCore.QRect(10, 50, 70, 17))
        self.rightButton.setObjectName("rightButton")
        self.frontButton = QtWidgets.QCheckBox(self.ViewBox)
        self.frontButton.setGeometry(QtCore.QRect(10, 80, 70, 17))
        self.frontButton.setObjectName("frontButton")
        self.backButton = QtWidgets.QCheckBox(self.ViewBox)
        self.backButton.setGeometry(QtCore.QRect(10, 110, 70, 17))
        self.backButton.setObjectName("backButton")
        self.topButton = QtWidgets.QCheckBox(self.ViewBox)
        self.topButton.setGeometry(QtCore.QRect(10, 140, 70, 17))
        self.topButton.setObjectName("topButton")
        self.bottomButton = QtWidgets.QCheckBox(self.ViewBox)
        self.bottomButton.setGeometry(QtCore.QRect(10, 170, 70, 17))
        self.bottomButton.setObjectName("bottomButton")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(150, 70, 261, 261))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Canvas = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.Canvas.setEnabled(True)
        self.Canvas.setMinimumSize(QtCore.QSize(256, 256))
        self.Canvas.setMaximumSize(QtCore.QSize(256, 256))
        self.Canvas.setPixmap(QtGui.QPixmap("multiview/Blank.png"))
        self.Canvas.setObjectName("Canvas")
        self.horizontalLayout.addWidget(self.Canvas)
        self.leftThumbnail = QtWidgets.QLabel(self.centralwidget)
        self.leftThumbnail.setEnabled(True)
        self.leftThumbnail.setGeometry(QtCore.QRect(20, 430, 36, 36))
        self.leftThumbnail.setText("")
        self.leftThumbnail.setPixmap(QtGui.QPixmap("multiview/Blank.png"))
        self.leftThumbnail.setScaledContents(True)
        self.leftThumbnail.setObjectName("leftThumbnail")
        self.eraserButton = QtWidgets.QPushButton(self.centralwidget)
        self.eraserButton.setGeometry(QtCore.QRect(10, 70, 30, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.eraserButton.sizePolicy().hasHeightForWidth())
        self.eraserButton.setSizePolicy(sizePolicy)
        self.eraserButton.setMinimumSize(QtCore.QSize(30, 30))
        self.eraserButton.setMaximumSize(QtCore.QSize(30, 30))
        self.eraserButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/eraser.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.eraserButton.setIcon(icon)
        self.eraserButton.setCheckable(True)
        self.eraserButton.setObjectName("eraserButton")
        self.penButton = QtWidgets.QPushButton(self.centralwidget)
        self.penButton.setGeometry(QtCore.QRect(60, 70, 30, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.penButton.sizePolicy().hasHeightForWidth())
        self.penButton.setSizePolicy(sizePolicy)
        self.penButton.setMinimumSize(QtCore.QSize(30, 30))
        self.penButton.setMaximumSize(QtCore.QSize(30, 30))
        self.penButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/pencil.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.penButton.setIcon(icon1)
        self.penButton.setCheckable(True)
        self.penButton.setChecked(True)
        self.penButton.setObjectName("penButton")
        self.colorButton_1 = QtWidgets.QPushButton(self.centralwidget)
        self.colorButton_1.setGeometry(QtCore.QRect(150, 10, 20, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colorButton_1.sizePolicy().hasHeightForWidth())
        self.colorButton_1.setSizePolicy(sizePolicy)
        self.colorButton_1.setMinimumSize(QtCore.QSize(20, 20))
        self.colorButton_1.setMaximumSize(QtCore.QSize(20, 13))
        self.colorButton_1.setStyleSheet("")
        self.colorButton_1.setText("")
        self.colorButton_1.setObjectName("colorButton_1")
        self.colorButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.colorButton_2.setGeometry(QtCore.QRect(190, 10, 20, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colorButton_2.sizePolicy().hasHeightForWidth())
        self.colorButton_2.setSizePolicy(sizePolicy)
        self.colorButton_2.setMinimumSize(QtCore.QSize(20, 20))
        self.colorButton_2.setMaximumSize(QtCore.QSize(20, 13))
        self.colorButton_2.setStyleSheet("")
        self.colorButton_2.setText("")
        self.colorButton_2.setObjectName("colorButton_2")
        self.colorButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.colorButton_3.setGeometry(QtCore.QRect(230, 10, 20, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colorButton_3.sizePolicy().hasHeightForWidth())
        self.colorButton_3.setSizePolicy(sizePolicy)
        self.colorButton_3.setMinimumSize(QtCore.QSize(20, 20))
        self.colorButton_3.setMaximumSize(QtCore.QSize(20, 13))
        self.colorButton_3.setStyleSheet("")
        self.colorButton_3.setText("")
        self.colorButton_3.setObjectName("colorButton_3")
        self.colorButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.colorButton_4.setGeometry(QtCore.QRect(270, 10, 20, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colorButton_4.sizePolicy().hasHeightForWidth())
        self.colorButton_4.setSizePolicy(sizePolicy)
        self.colorButton_4.setMinimumSize(QtCore.QSize(20, 20))
        self.colorButton_4.setMaximumSize(QtCore.QSize(20, 13))
        self.colorButton_4.setStyleSheet("")
        self.colorButton_4.setText("")
        self.colorButton_4.setObjectName("colorButton_4")
        self.colorButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.colorButton_5.setGeometry(QtCore.QRect(310, 10, 20, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colorButton_5.sizePolicy().hasHeightForWidth())
        self.colorButton_5.setSizePolicy(sizePolicy)
        self.colorButton_5.setMinimumSize(QtCore.QSize(20, 20))
        self.colorButton_5.setMaximumSize(QtCore.QSize(20, 13))
        self.colorButton_5.setStyleSheet("")
        self.colorButton_5.setText("")
        self.colorButton_5.setObjectName("colorButton_5")
        self.colorButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.colorButton_6.setGeometry(QtCore.QRect(150, 40, 20, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colorButton_6.sizePolicy().hasHeightForWidth())
        self.colorButton_6.setSizePolicy(sizePolicy)
        self.colorButton_6.setMinimumSize(QtCore.QSize(20, 20))
        self.colorButton_6.setMaximumSize(QtCore.QSize(20, 13))
        self.colorButton_6.setStyleSheet("")
        self.colorButton_6.setText("")
        self.colorButton_6.setObjectName("colorButton_6")
        self.colorButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.colorButton_7.setGeometry(QtCore.QRect(190, 40, 20, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colorButton_7.sizePolicy().hasHeightForWidth())
        self.colorButton_7.setSizePolicy(sizePolicy)
        self.colorButton_7.setMinimumSize(QtCore.QSize(20, 20))
        self.colorButton_7.setMaximumSize(QtCore.QSize(20, 13))
        self.colorButton_7.setStyleSheet("")
        self.colorButton_7.setText("")
        self.colorButton_7.setObjectName("colorButton_7")
        self.colorButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.colorButton_8.setGeometry(QtCore.QRect(230, 40, 20, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colorButton_8.sizePolicy().hasHeightForWidth())
        self.colorButton_8.setSizePolicy(sizePolicy)
        self.colorButton_8.setMinimumSize(QtCore.QSize(20, 20))
        self.colorButton_8.setMaximumSize(QtCore.QSize(20, 13))
        self.colorButton_8.setStyleSheet("")
        self.colorButton_8.setText("")
        self.colorButton_8.setObjectName("colorButton_8")
        self.colorButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.colorButton_9.setGeometry(QtCore.QRect(270, 40, 20, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colorButton_9.sizePolicy().hasHeightForWidth())
        self.colorButton_9.setSizePolicy(sizePolicy)
        self.colorButton_9.setMinimumSize(QtCore.QSize(20, 20))
        self.colorButton_9.setMaximumSize(QtCore.QSize(20, 13))
        self.colorButton_9.setStyleSheet("")
        self.colorButton_9.setText("")
        self.colorButton_9.setObjectName("colorButton_9")
        self.colorButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.colorButton_10.setGeometry(QtCore.QRect(310, 40, 20, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colorButton_10.sizePolicy().hasHeightForWidth())
        self.colorButton_10.setSizePolicy(sizePolicy)
        self.colorButton_10.setMinimumSize(QtCore.QSize(20, 20))
        self.colorButton_10.setMaximumSize(QtCore.QSize(20, 13))
        self.colorButton_10.setStyleSheet("")
        self.colorButton_10.setText("")
        self.colorButton_10.setObjectName("colorButton_10")
        self.rightThumbnail = QtWidgets.QLabel(self.centralwidget)
        self.rightThumbnail.setGeometry(QtCore.QRect(20, 480, 36, 36))
        self.rightThumbnail.setText("")
        self.rightThumbnail.setPixmap(QtGui.QPixmap("multiview/Blank.png"))
        self.rightThumbnail.setScaledContents(True)
        self.rightThumbnail.setObjectName("rightThumbnail")
        self.frontThumbnail = QtWidgets.QLabel(self.centralwidget)
        self.frontThumbnail.setGeometry(QtCore.QRect(20, 530, 36, 36))
        self.frontThumbnail.setText("")
        self.frontThumbnail.setPixmap(QtGui.QPixmap("multiview/Blank.png"))
        self.frontThumbnail.setScaledContents(True)
        self.frontThumbnail.setObjectName("frontThumbnail")
        self.backThumbnail = QtWidgets.QLabel(self.centralwidget)
        self.backThumbnail.setGeometry(QtCore.QRect(20, 580, 36, 36))
        self.backThumbnail.setText("")
        self.backThumbnail.setPixmap(QtGui.QPixmap("multiview/Blank.png"))
        self.backThumbnail.setScaledContents(True)
        self.backThumbnail.setObjectName("backThumbnail")
        self.topThumbnail = QtWidgets.QLabel(self.centralwidget)
        self.topThumbnail.setGeometry(QtCore.QRect(20, 630, 36, 36))
        self.topThumbnail.setText("")
        self.topThumbnail.setPixmap(QtGui.QPixmap("multiview/Blank.png"))
        self.topThumbnail.setScaledContents(True)
        self.topThumbnail.setObjectName("topThumbnail")
        self.bottomThumbnail = QtWidgets.QLabel(self.centralwidget)
        self.bottomThumbnail.setGeometry(QtCore.QRect(20, 680, 36, 36))
        self.bottomThumbnail.setText("")
        self.bottomThumbnail.setPixmap(QtGui.QPixmap("multiview/Blank.png"))
        self.bottomThumbnail.setObjectName("bottomThumbnail")
        self.leftlabel = QtWidgets.QLabel(self.centralwidget)
        self.leftlabel.setEnabled(False)
        self.leftlabel.setGeometry(QtCore.QRect(70, 440, 47, 13))
        self.leftlabel.setObjectName("leftlabel")
        self.rightlabel = QtWidgets.QLabel(self.centralwidget)
        self.rightlabel.setEnabled(False)
        self.rightlabel.setGeometry(QtCore.QRect(70, 490, 47, 13))
        self.rightlabel.setObjectName("rightlabel")
        self.frontlabel = QtWidgets.QLabel(self.centralwidget)
        self.frontlabel.setEnabled(False)
        self.frontlabel.setGeometry(QtCore.QRect(70, 540, 47, 13))
        self.frontlabel.setObjectName("frontlabel")
        self.backlabel = QtWidgets.QLabel(self.centralwidget)
        self.backlabel.setEnabled(False)
        self.backlabel.setGeometry(QtCore.QRect(70, 590, 47, 13))
        self.backlabel.setObjectName("backlabel")
        self.toplabel = QtWidgets.QLabel(self.centralwidget)
        self.toplabel.setEnabled(False)
        self.toplabel.setGeometry(QtCore.QRect(70, 640, 47, 13))
        self.toplabel.setObjectName("toplabel")
        self.bottomlabel = QtWidgets.QLabel(self.centralwidget)
        self.bottomlabel.setEnabled(False)
        self.bottomlabel.setGeometry(QtCore.QRect(70, 690, 47, 13))
        self.bottomlabel.setObjectName("bottomlabel")
        self.ThumbnailListView = QtWidgets.QListWidget(self.centralwidget)
        self.ThumbnailListView.setGeometry(QtCore.QRect(430, 70, 121, 261))
        self.ThumbnailListView.setObjectName("ThumbnailListView")
        self.fillButton = QtWidgets.QPushButton(self.centralwidget)
        self.fillButton.setGeometry(QtCore.QRect(110, 70, 30, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fillButton.sizePolicy().hasHeightForWidth())
        self.fillButton.setSizePolicy(sizePolicy)
        self.fillButton.setMinimumSize(QtCore.QSize(30, 30))
        self.fillButton.setMaximumSize(QtCore.QSize(30, 30))
        self.fillButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/paint-can.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fillButton.setIcon(icon2)
        self.fillButton.setCheckable(True)
        self.fillButton.setChecked(False)
        self.fillButton.setObjectName("fillButton")
        PaintWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(PaintWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 21))
        self.menubar.setObjectName("menubar")
        self.menuOperations = QtWidgets.QMenu(self.menubar)
        self.menuOperations.setObjectName("menuOperations")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        PaintWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(PaintWindow)
        self.statusbar.setObjectName("statusbar")
        PaintWindow.setStatusBar(self.statusbar)
        self.actionSave = QtWidgets.QAction(PaintWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/disk.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon3)
        self.actionSave.setObjectName("actionSave")
        self.actionNew = QtWidgets.QAction(PaintWindow)
        self.actionNew.setEnabled(True)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/document-image.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNew.setIcon(icon4)
        self.actionNew.setObjectName("actionNew")
        self.action3px = QtWidgets.QAction(PaintWindow)
        self.action3px.setObjectName("action3px")
        self.action5px = QtWidgets.QAction(PaintWindow)
        self.action5px.setObjectName("action5px")
        self.action7px = QtWidgets.QAction(PaintWindow)
        self.action7px.setObjectName("action7px")
        self.action9px = QtWidgets.QAction(PaintWindow)
        self.action9px.setObjectName("action9px")
        self.actionBlack = QtWidgets.QAction(PaintWindow)
        self.actionBlack.setObjectName("actionBlack")
        self.actionWhite = QtWidgets.QAction(PaintWindow)
        self.actionWhite.setObjectName("actionWhite")
        self.actionRed = QtWidgets.QAction(PaintWindow)
        self.actionRed.setObjectName("actionRed")
        self.actionGreen = QtWidgets.QAction(PaintWindow)
        self.actionGreen.setObjectName("actionGreen")
        self.actionOpen = QtWidgets.QAction(PaintWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icons/blue-folder-open-image.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon5)
        self.actionOpen.setObjectName("actionOpen")
        self.actionClear = QtWidgets.QAction(PaintWindow)
        self.actionClear.setObjectName("actionClear")
        self.menuOperations.addAction(self.actionNew)
        self.menuOperations.addAction(self.actionOpen)
        self.menuOperations.addAction(self.actionSave)
        self.menuEdit.addAction(self.actionClear)
        self.menubar.addAction(self.menuOperations.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())

        self.retranslateUi(PaintWindow)
        QtCore.QMetaObject.connectSlotsByName(PaintWindow)

    def retranslateUi(self, PaintWindow):
        _translate = QtCore.QCoreApplication.translate
        PaintWindow.setWindowTitle(_translate("PaintWindow", "Paint View"))
        self.AddButton.setText(_translate("PaintWindow", "Add"))
        self.InitializeButton.setText(_translate("PaintWindow", "Initialize"))
        self.UpdateButton.setText(_translate("PaintWindow", "Update"))
        self.ViewBox.setTitle(_translate("PaintWindow", "View"))
        self.leftButton.setText(_translate("PaintWindow", "Left"))
        self.rightButton.setText(_translate("PaintWindow", "Right"))
        self.frontButton.setText(_translate("PaintWindow", "Front"))
        self.backButton.setText(_translate("PaintWindow", "Back"))
        self.topButton.setText(_translate("PaintWindow", "Top"))
        self.bottomButton.setText(_translate("PaintWindow", "Bottom"))
        self.leftlabel.setText(_translate("PaintWindow", "Left"))
        self.rightlabel.setText(_translate("PaintWindow", "Right"))
        self.frontlabel.setText(_translate("PaintWindow", "Front"))
        self.backlabel.setText(_translate("PaintWindow", "Back"))
        self.toplabel.setText(_translate("PaintWindow", "Top"))
        self.bottomlabel.setText(_translate("PaintWindow", "Bottom"))
        self.menuOperations.setTitle(_translate("PaintWindow", "File"))
        self.menuEdit.setTitle(_translate("PaintWindow", "Edit"))
        self.actionSave.setText(_translate("PaintWindow", "Save as Image"))
        self.actionNew.setText(_translate("PaintWindow", "New Image"))
        self.action3px.setText(_translate("PaintWindow", "3px"))
        self.action5px.setText(_translate("PaintWindow", "5px"))
        self.action7px.setText(_translate("PaintWindow", "7px"))
        self.action9px.setText(_translate("PaintWindow", "9px"))
        self.actionBlack.setText(_translate("PaintWindow", "Black"))
        self.actionWhite.setText(_translate("PaintWindow", "White"))
        self.actionRed.setText(_translate("PaintWindow", "Red"))
        self.actionGreen.setText(_translate("PaintWindow", "Green"))
        self.actionOpen.setText(_translate("PaintWindow", "Open Image"))
        self.actionClear.setText(_translate("PaintWindow", "Clear Image"))
